# Generated by Django 5.1.6 on 2025-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_construction_expense',
            field=models.BooleanField(default=False),
        ),
    ]
